apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: fzgi7w0tj-go 
  janus-idp.io/tekton: fzgi7w0tj-go
  backstage.io/kubernetes-id: fzgi7w0tj-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: fzgi7w0tj-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  