apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: fzgi7w0tj-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: fzgi7w0tj-go 
  name: fzgi7w0tj-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: fzgi7w0tj-go 
